data_root : Data

data_ingestion:
  row_data: C:\Users\Sajid\Documents\Deep Sequence\data\raw
  url_sources: str
  file_data: 'FB_DL.csv'


data_processing:
  file_path: C:\Users\Sajid\Documents\Deep Sequence\data\raw\FB_DL.csv
  window_size: 10
  target: Volume
  index_colume: Date

prepare_callbacks:
  root_path_log: C:\Users\Sajid\Documents\Deep Sequence\
  tensorboard_root_log_dir: C:\Users\Sajid\Documents\Deep Sequence\log_dir
  checkpoint_model_filepath: C:\Users\Sajid\Documents\Deep Sequence\models\callbacks

train_model:
  best_model_path: C:\Users\Sajid\Documents\Deep Sequence\models\best_model



prepare_base_model:
  model_root : C:\Users\Sajid\Documents\Deep Sequence\models
